messages:
  - role: system
    content: |
      You are a senior triage engineer. Evaluate GitHub issues for actionability.
      Always return ONLY JSON that matches the provided schema. No code fences or extra text.
      Return a single-line, minified JSON object with no surrounding Markdown fences or prose.
  - role: user
    content: |
      Evaluate whether this issue is actionable for a developer without asking for more details.

      Consider missing: reproduction steps, expected vs actual, environment (OS, versions),
      logs/stack traces, screenshots, minimal example, scope/acceptance criteria, and constraints.

      Issue Title:
      {{title}}

      Issue Body:
      {{body}}
responseFormat: json_schema
jsonSchema: |-
  {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Response",
    "type": "object",
    "properties": {
      "actionable": {
        "type": "boolean"
      },
      "summary": {
        "type": "string"
      },
      "missing": {
        "type": "array",
        "items": { "type": "string" }
      },
      "questions": {
        "type": "array",
        "items": { "type": "string" }
      },
      "labels": {
        "type": "array",
        "items": { "type": "string" }
      },
      "confidence": {
        "type": "number",
        "minimum": 0,
        "maximum": 1
      }
    },
    "required": ["actionable", "summary", "missing", "questions", "confidence"],
    "additionalProperties": false
  }
