name: Judge and Summarize PR with AI

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  judge-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get PR summary and diff
        id: pr_info
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });
            const diff = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              mediaType: { format: "diff" }
            });
            return {
              summary: pr.data.body || "",
              diff: diff.data
            };

      - name: Judge PR summary using AI
        id: ai_judge
        uses: actions/ai-inference@v1
        with:
          task: "text-classification"
          inputs: |
            [
              {
                "summary": "${{ steps.pr_info.outputs.summary }}",
                "diff": "${{ steps.pr_info.outputs.diff }}"
              }
            ]
          model: "gpt-4"
          prompt: |
            You are an AI reviewer. Given the PR summary and the diff, judge whether the summary accurately reflects the changes. Respond "fit" if it fits, otherwise respond "not fit".

      - name: Generate new summary if needed
        if: steps.ai_judge.outputs.result == 'not fit'
        uses: actions/ai-inference@v1
        id: ai_summary
        with:
          task: "text-generation"
          inputs: "${{ steps.pr_info.outputs.diff }}"
          model: "gpt-4"
          prompt: |
            You are an AI reviewer. Based on the following PR diff, generate a clear and concise summary describing the changes for the PR description.

      - name: Comment summary on PR
        if: steps.ai_judge.outputs.result == 'not fit'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `AI-generated summary (original did not fit the changes):\n\n${{ steps.ai_summary.outputs.result }}`
            });
